
package chatsocket;


import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;
import controller.MessController;
import model.Message;
import java.util.ArrayList;
import model.Group;
import controller.GroupController;


public class ChatGroupFrame extends javax.swing.JFrame {

    private static String src;
    private static String desuser;
    private static ClientHandle client;
    private static String mess;
    private static MessController mctr;
    private static GroupController gctr;
    private ArrayList<String> list;
    private static boolean stt = false;
    

    
    
    /**
     * Creates new form ChatPrivate
     */
    public ChatGroupFrame(String src,String des, ClientHandle client,String mess) {
        initComponents();
        mctr = new MessController();
            gctr = new GroupController();
        this.src = src;
        this.desuser=des;
        this.client = client;
        
        this.list = mctr.getMessGroup(des);
//        
//        list.stream().forEachOrdered(m -> {
//            appendmess(m);
//        });
        list.forEach((m) -> {
            appendmess(m);
        });
                
        this.mess = mess;
        txtUsername.setText(des);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(ChatGroupFrame.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                client.WriteExitPrivateClient(des);
            }
        });
        System.out.println("Thread init frame"+Thread.currentThread().getName());
        this.addWindowFocusListener(new WindowFocusListener(){
            @Override
            public void windowGainedFocus(WindowEvent e) {
                System.out.println(txtUsername.getText());
                desuser = txtUsername.getText();
            }

            @Override
            public void windowLostFocus(WindowEvent e) {
                System.out.println("nothing");
            }
            
        });
    }
    
    public static void  getInfo(String username, String mess){
        ChatGroupFrame.desuser = username;
        ChatGroupFrame.mess = mess;
        ChatGroupFrame.stt = true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JLabel();
        txtChatPrivate = new javax.swing.JTextField();
        btnSendPrivate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneChatPrivate = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsername.setText("Groupname");

        txtChatPrivate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChatPrivateKeyPressed(evt);
            }
        });

        btnSendPrivate.setText("Send");
        btnSendPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPrivateActionPerformed(evt);
            }
        });

        jTextPaneChatPrivate.setEnabled(false);
        jTextPaneChatPrivate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPaneChatPrivateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPaneChatPrivate);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtChatPrivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendPrivate))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUsername)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChatPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPrivateActionPerformed
        // TODO add your handling code here:
        
        String mess = txtChatPrivate.getText();
        if(!mess.isEmpty()){
            client.WriteChatGroup(desuser, mess);
            
            txtChatPrivate.setText("");
            Message x = new Message(mess, "Group",desuser, src );
            mctr.insertMess(x);
//            System.out.println(txtUsername.getText());
            
        }
        
    }//GEN-LAST:event_btnSendPrivateActionPerformed

    private void txtChatPrivateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChatPrivateKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String mess = txtChatPrivate.getText();
            client.WriteChatGroup(desuser, mess);
            txtChatPrivate.setText("");
            System.out.println(txtUsername.getText());
        }
        
    }//GEN-LAST:event_txtChatPrivateKeyPressed
    
    private void jTextPaneChatPrivateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPaneChatPrivateMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextPaneChatPrivateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String userName = jTextField1.getText();
        String mess = userName+":"+this.desuser+":AddGroup";
        Group group = new Group(this.desuser);
        gctr.addUser(group, userName);
        client.WriteClient(mess);
        jTextField1.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void appendmess(String mess){
        //txtareaChatPrivate.append(mess+"\n");
        String newms = mess+"\n";
        StyledDocument doc = jTextPaneChatPrivate.getStyledDocument();
        try {
            doc.insertString(doc.getLength(), newms, null );
        } catch (BadLocationException ex) {
            Logger.getLogger(ChatGroupFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    public void appendStringForTextPane(String str){
        StyledDocument doc = jTextPaneChatPrivate.getStyledDocument();
        try {
            doc.insertString(doc.getLength(), str, null );
        } catch (BadLocationException ex) {
            Logger.getLogger(ChatGroupFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatGroupFrame(src,desuser,client,mess).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendPrivate;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPaneChatPrivate;
    private javax.swing.JTextField txtChatPrivate;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
